### ISSUE TITLE
Template packge

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/Meta#8]
Would there be a use for a "template package" that has everything configured and set up properly with new packages just needing to modify little bits of the code to get a working linter plugin?

**Comment by steelbrain** [comment]
I love the idea, mostly people just need to configure the executable and the regex, everything else can be generic for most linters

**Comment by mysablehats** [comment]
Any idea if this will ever get done? Or is there a package that is just simple enough so that I can look and implement this myself?
I wanted just to hook up http://wiki.ros.org/roslint to atom-linter so that atom could also support ros packages. 
I am currently setting up  https://github.com/hebaishi/linter-gcc with a bunch of arguments, but it does not seem to make a lot of sense not to have this automated. 
Any help would be appreciated!

**Comment by Arcanemagus** [comment]
That's probably one of the least helpful ones to base something off of due to the messiness of launching `gcc` 😆.

If `roslint` outputs text directly in an easily parsable format something like [linter-flake8](https://github.com/AtomLinter/linter-flake8/blob/master/lib/main.js) is probably a better choice. There are a _lot_ of different things you can do though, feel free to contact me on [Atom's Slack](https://discuss.atom.io/t/join-us-on-slack/16638) if you have any questions.

**Comment by Arcanemagus** [comment]
This has been created at [linter-template](https://github.com/AtomLinter/linter-template), any changes to the template should be filed there.
